Create User model
CraftAcademy/laundry_time pull request #13
Opened 2017-09-26 09:59 UTC by nurlanemir

## PT link: https://www.pivotaltracker.com/story/show/151431172 ##
- Added devise gem
- Added User model
- Added User controller

What we've learned: 
- How authentication mechanism works with Rails

2017-09-26 10:19 UTC, diraulo commented
@nurlanemir we need to clean your commit history here... I suspect your `develop` branch is messed up.

2017-09-26 12:35 UTC, diraulo submitted a review, later dismissed
Commit history looks good now but this PR has no tests at all? why?

2017-09-26 12:35 UTC, diraulo commented on spec/models/user_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
No tests for the user model? 🤔

2017-09-27 04:39 UTC, tochman requested changes
You need to add more tests for the sad path (error handlers) and also unit specs for the user.

2017-09-27 04:39 UTC, tochman commented on features/step_definitions/user_registration_steps.rb
> +      User.create!(hash)
1. We don't use methods with a `!` unless there´s a really good reason. What would be the reason here? 
2. There's a gem called FactoryGirl installed. We used that gem in the Rails Messaging Legacy Code Challenge. Why not use it here?

2017-09-27 04:39 UTC, tochman commented on features/user_registration.feature
> +    I should be able to sign up for account
The user story format has 3 components. This story only has 2. What is missing?

2017-09-27 08:25 UTC, tochman requested changes
I don't see a reason why you have generated all the views for devise. I will let it pass but there is no need to do that at this stage. The authentication would have worked anyway. (See my other comments)

2017-09-27 08:25 UTC, tochman commented on app/controllers/user_controller.rb
> +end
Why is this controller created and why do you have a `new`method? Try running your tests without it.

2017-09-27 08:50 UTC, tochman approved these changes

2017-09-27 09:03 UTC, merged